services:
  idp:
    image: sample-idp:latest
    environment:
      JWT_SECRET: "${JWT_SECRET:-secret}"
      JWT_PUBLIC: "${JWT_PUBLIC:-}"
      MAILER: "${MAILER:-mailcatcher}"
      FROM_ADDRESS: "${FROM:-idp@localhost}"
      MAILSLURP_API_KEY: "${MAILSLURP_API_KEY:-}"
    volumes:
      - ./src:/app/src
      - ./routes/:/app/routes
      - ./islands/:/app/islands
      - ./deno.json:/app/deno.json
      - ./fresh.gen.ts:/app/fresh.gen.ts
      - ./fresh.config.ts:/app/fresh.config.ts
    ports:
      - 8080:8000
    depends_on:
      - mailcatcher

  mailcatcher:
    image: dockage/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025
