services:
  idp:
    image: mstysk/idp:latest
    environment:
      JTW_KEY: "${JTW_KEY:-secret}"
      MAILER: "${MAILER:-mailcatcher}"
      FROM_ADDRESS: "${FROM:-idp@localhost}"
      MAILSLURP_API_KEY: "${MAILSLURP_API_KEY:-}"
    volumes:
      - ./src:/app/src
      - ./routes/:/app/routes
      - ./deno.json:/app/deno.json
      - ./fresh.gen.ts:/app/fresh.gen.ts
      - ./fresh.config.ts:/app/fresh.config.ts
    ports:
      - 8080:8000
    depends_on:
      - mailcatcher

  mailcatcher:
    image: dockage/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025
